In [30]:
import os
import pandas as pd

In [31]:
ROOT_DIR = os.path.dirname(os.getcwd())

ROOT_DIR

'/home/matheus/Desktop/Projs/gym-auto-planner'

In [32]:
df_raw = pd.read_csv(os.path.join(ROOT_DIR, 'datasets', 'gym_exercise_dataset.csv'))

df_raw.head()

,Exercise Name,Equipment,Variation,Utility,Mechanics,Force,Preparation,Execution,Target_Muscles,Synergist_Muscles,Stabilizer_Muscles,Antagonist_Muscles,Dynamic_Stabilizer_Muscles,Main_muscle,Difficulty (1-5),Secondary Muscles,parent_id
0,Neck Flexion,Cable,No,Basic or Auxiliary,Isolated,Pull,Sit on bench facing away from middle pulley. P...,Move head away from pulley by bending neck for...,"Sternocleidomastoid,","None,","Rectus Abdominis,Obliques,",NaN,NaN,Neck,2,Sternocleidomastoid,NaN
1,Neck Flexion,Lever (plate loaded),No,Basic or Auxiliary,Isolated,Pull,Sit on seat in machine. Position padded lever ...,Move head forward by flexing neck until chin t...,"Sternocleidomastoid,","None,","Latissimus Dorsi,Posterior Deltoid,Rhomboids,U...",NaN,NaN,Neck,2,Sternocleidomastoid,NaN
2,Lateral Neck Flexion,Lever (plate loaded),No,Auxiliary,Isolated,Pull,Sit on seat in machine with feet apart . Pos...,Move head down to side by laterally flexing ne...,"Sternocleidomastoid,","Splenius,Erector Spinae,Levator Scapulae,Upper...","Latissimus Dorsi,Pectoralis Major Sternal,Cora...",NaN,NaN,Neck,2,"Sternocleidomastoid,Levator Scapulae",NaN
3,Neck Flexion,Lever (selectorized),No,Basic or Auxiliary,Isolated,Pull,Sit on seat in machine. Position padded lever ...,Move head forward by flexing neck until chin t...,"Sternocleidomastoid,","None,","Latissimus Dorsi,Posterior Deltoid,Rhomboids,U...",NaN,NaN,Neck,2,Sternocleidomastoid,NaN
4,Lateral Neck Flexion,Lever (selectorized),No,Auxiliary,Isolated,Pull,Sit on seat in machine with feet apart. Positi...,Move head down to side by laterally flexing ne...,"Sternocleidomastoid,","Splenius,Erector Spinae,Levator Scapulae,Upper...","Latissimus Dorsi,Pectoralis Major Sternal,Cora...",NaN,NaN,Neck,2,"Sternocleidomastoid,Levator Scapulae",NaN

In [33]:
df_raw.columns

Index(['Exercise Name', 'Equipment', 'Variation', 'Utility', 'Mechanics',
       'Force', 'Preparation', 'Execution', 'Target_Muscles',
       'Synergist_Muscles', 'Stabilizer_Muscles', 'Antagonist_Muscles',
       'Dynamic_Stabilizer_Muscles', 'Main_muscle', 'Difficulty (1-5)',
       'Secondary Muscles', 'parent_id'],
      dtype='str')

In [34]:
muscle_groups = df_raw[['Target_Muscles', 'Synergist_Muscles', 'Stabilizer_Muscles', 'Antagonist_Muscles', 'Dynamic_Stabilizer_Muscles', 'Secondary Muscles']]

muscle_groups.head()

,Target_Muscles,Synergist_Muscles,Stabilizer_Muscles,Antagonist_Muscles,Dynamic_Stabilizer_Muscles,Secondary Muscles
0,"Sternocleidomastoid,","None,","Rectus Abdominis,Obliques,",NaN,NaN,Sternocleidomastoid
1,"Sternocleidomastoid,","None,","Latissimus Dorsi,Posterior Deltoid,Rhomboids,U...",NaN,NaN,Sternocleidomastoid
2,"Sternocleidomastoid,","Splenius,Erector Spinae,Levator Scapulae,Upper...","Latissimus Dorsi,Pectoralis Major Sternal,Cora...",NaN,NaN,"Sternocleidomastoid,Levator Scapulae"
3,"Sternocleidomastoid,","None,","Latissimus Dorsi,Posterior Deltoid,Rhomboids,U...",NaN,NaN,Sternocleidomastoid
4,"Sternocleidomastoid,","Splenius,Erector Spinae,Levator Scapulae,Upper...","Latissimus Dorsi,Pectoralis Major Sternal,Cora...",NaN,NaN,"Sternocleidomastoid,Levator Scapulae"

In [35]:
muscle_groups['full_set'] = muscle_groups.fillna('').astype(str).agg(','.join, axis=1).replace('\n', '', regex=True).replace(r'\(.*?\)', '', regex=True).replace(r'[0-9]', '', regex=True).replace('None', '')


muscle_groups.head()

,Target_Muscles,Synergist_Muscles,Stabilizer_Muscles,Antagonist_Muscles,Dynamic_Stabilizer_Muscles,Secondary Muscles,full_set
0,"Sternocleidomastoid,","None,","Rectus Abdominis,Obliques,",NaN,NaN,Sternocleidomastoid,"Sternocleidomastoid,,None,,Rectus Abdominis,Ob..."
1,"Sternocleidomastoid,","None,","Latissimus Dorsi,Posterior Deltoid,Rhomboids,U...",NaN,NaN,Sternocleidomastoid,"Sternocleidomastoid,,None,,Latissimus Dorsi,Po..."
2,"Sternocleidomastoid,","Splenius,Erector Spinae,Levator Scapulae,Upper...","Latissimus Dorsi,Pectoralis Major Sternal,Cora...",NaN,NaN,"Sternocleidomastoid,Levator Scapulae","Sternocleidomastoid,,Splenius,Erector Spinae,L..."
3,"Sternocleidomastoid,","None,","Latissimus Dorsi,Posterior Deltoid,Rhomboids,U...",NaN,NaN,Sternocleidomastoid,"Sternocleidomastoid,,None,,Latissimus Dorsi,Po..."
4,"Sternocleidomastoid,","Splenius,Erector Spinae,Levator Scapulae,Upper...","Latissimus Dorsi,Pectoralis Major Sternal,Cora...",NaN,NaN,"Sternocleidomastoid,Levator Scapulae","Sternocleidomastoid,,Splenius,Erector Spinae,L..."

In [36]:
list_muscles = [group.split(',') for group in muscle_groups['full_set'].tolist()]

list_muscles = [muscle.strip() for group in list_muscles for muscle in group]

set(list_muscles)

{'',
 'Adductor Brevis',
 'Adductor Longus',
 'Adductor Magnus',
 'Anterior Deltoid',
 'Biceps Brachii',
 'Brachialis',
 'Brachioradialis',
 'Cervicis and Capitis Fibers',
 'Coracobrachialis',
 'Erector Spinae',
 'Extensor Carpi Radialis',
 'Extensor Carpi Ulnaris',
 'Flexor Carpi Radialis',
 'Flexor Carpi Ulnaris',
 'Gastrocnemius',
 'Gluteus Maximus',
 'Gluteus Medius',
 'Gluteus Minimus',
 'Gracilis',
 'Hamstrings',
 'Hip Flexors',
 'Iliocastalis lumborum',
 'Iliocastalis thoracis',
 'Iliopsoas',
 'Inferior Digitations',
 'Infraspinatus',
 'Lateral Deltoid',
 'Latissimus Dorsi',
 'Levator Scapulae',
 'Longus capitis',
 'Longus colli',
 'Lower Trapezius',
 'Middle Trapezius',
 'None',
 'Obliques',
 'Obturator externus',
 'Pectineus',
 'Pectoralis Major Clavicular',
 'Pectoralis Major Sternal',
 'Pectoralis Minor',
 'Piriformis',
 'Popliteus',
 'Posterior Deltoid',
 'Pronators',
 'Psoas major',
 'Quadratus Lumborum',
 'Quadriceps',
 'Rectus Abdominis',
 'Rectus Femoris',
 'Rectus capitus',
 'Rhomboids',
 'Sartorius',
 'Serratus Anterior',
 'Soleus',
 'Splenius',
 'Sternocleidomastoid',
 'Subscapularis',
 'Supinator',
 'Supraspinatus',
 'Tensor Fasciae Latae',
 'Teres Major',
 'Teres Minor',
 'Tibialis Anterior',
 'Triceps Brachii',
 'Upper Trapezius',
 'Wrist Extensors',
 'Wrist Flexors'}

In [13]:
muscle_groups['target_count'] = muscle_groups.apply(lambda x: len([m for m in x['Target_Muscles'].split(',') if len(m.strip()) > 0]), axis=1)

muscle_groups[muscle_groups['target_count'] > 1]

,Target_Muscles,Synergist_Muscles,Stabilizer_Muscles,Antagonist_Muscles,Dynamic_Stabilizer_Muscles,Secondary Muscles,full_set,target_count
166,"Latissimus Dorsi, Lower Trapezius, Rhomboids, ...","Trapezius, Middle, Trapezius, Lower, Rhomboids...","Erector Spinae, Hamstrings, Gluteus Maximus, A...","Rectus Abdominis, Obliques,","Biceps Brachii, Triceps, Long Head,","Biceps Brachii, Trapezius, Rhomboids","Latissimus Dorsi, Lower Trapezius, Rhomboids, ...",4
167,"Latissimus Dorsi, Lower Trapezius, Rhomboids, ...","Latissimus Dorsi, Teres Major, Deltoid, Poster...","Erector Spinae, Hamstrings, Gluteus Maximus, A...","Rectus Abdominis, Obliques,","Biceps Brachii, Triceps, Long Head,","Biceps Brachii, Trapezius, Rhomboids","Latissimus Dorsi, Lower Trapezius, Rhomboids, ...",4
168,"Latissimus Dorsi, Lower Trapezius, Rhomboids, ...","Trapezius, Middle, Trapezius, Lower, Rhomboids...","Obliques, Hamstrings, Gluteus Maximus, Triceps...",NaN,"Biceps Brachii, Triceps, Long Head,","Biceps Brachii, Trapezius, Rhomboids","Latissimus Dorsi, Lower Trapezius, Rhomboids, ...",4
169,"Latissimus Dorsi, Lower Trapezius, Rhomboids, ...","Trapezius, Middle, Trapezius, Lower, Rhomboids...","Erector Spinae, Obliques, Quadratus Lumborum,","Rectus Abdominis,","Biceps Brachii, Triceps, Long Head,","Biceps Brachii, Trapezius, Rhomboids","Latissimus Dorsi, Lower Trapezius, Rhomboids, ...",4
170,"Latissimus Dorsi, Lower Trapezius, Rhomboids, ...","Erector Spinae, Trapezius, Middle, Trapezius, ...","Hamstrings, Gluteus Maximus, Adductor Magnus,",NaN,"Biceps Brachii, Triceps, Long Head,","Biceps Brachii, Trapezius, Rhomboids","Latissimus Dorsi, Lower Trapezius, Rhomboids, ...",4
...,...,...,...,...,...,...,...,...
253,"Infraspinatus, Teres Minor,","Teres Minor, Deltoid, Posterior,","Rhomboids, Trapezius, Lower, Wrist Extensors,",NaN,NaN,"Infraspinatus, Teres Minor","Infraspinatus, Teres Minor,Infraspinatus, Tere...",2
254,"Infraspinatus, Teres Minor,","Infraspinatus, Deltoid, Posterior, Supraspinat...","Serratus Anterior, Wrist Extensors,",NaN,NaN,"Infraspinatus, Teres Minor","Infraspinatus, Teres Minor,Infraspinatus, Tere...",2
255,"Infraspinatus, Teres Minor,","Infraspinatus, Deltoid, Posterior, Supraspinat...","Serratus Anterior, Wrist Extensors,",NaN,NaN,"Infraspinatus, Teres Minor","Infraspinatus, Teres Minor,Infraspinatus, Tere...",2
256,"Infraspinatus, Teres Minor,","Teres Minor, Deltoid, Posterior,","Trapezius, Lower, Wrist Extensors,",NaN,NaN,"Infraspinatus, Teres Minor","Infraspinatus, Teres Minor,Infraspinatus, Tere...",2
257,"Infraspinatus, Teres Minor,","Teres Minor, Deltoid, Posterior, Trapezius, Mi...","Latissimus Dorsi, Teres Major, Wrist Extensors...",NaN,NaN,"Infraspinatus, Teres Minor","Infraspinatus, Teres Minor,Infraspinatus, Tere...",2

In [14]:
df_raw['Equipment'].apply(lambda x: ' '.join(x.split()).replace('\u200b','')).drop_duplicates().to_list()

['Cable',
 'Lever (plate loaded)',
 'Lever (selectorized)',
 'Weighted',
 'Body Weight',
 'Suspended',
 'Band Resistive',
 'Isometric',
 'Barbell',
 'Dumbbell',
 'Sled',
 'Smith',
 'Assisted',
 'Band-assisted',
 'Self-assisted',
 'Sled (selectorized)',
 'Sled (plate loaded)',
 'Assisted (machine)',
 'Assisted (partner)',
 'Suspension',
 'Plyometric',
 'Assisted Chest Dip',
 'Cable Standing Fly',
 'Lever (selectorized) Chest Dip',
 'Weighted Chest Dip',
 'Cable (pull side)',
 'Lever']